### ISSUE TITLE
SpringBootアプリのベースを作成する

### ISSUE THREAD

**Issue by masatanish** [ayabe2000/nutrition_app_java#14]
何か一つのHTMLを表示する単純なSpringBootのアプリを作ってCommitしてください。
これをベースに他の機能を作り込んでいく方が良いと考えるためです。

**Comment by ayabe2000** [comment]
すみません、質問なのですが、
現状Spring Bootアプリケーションがデータベース接続のための設定を見つけることができないというエラーが出てしまい、進められていない状態です。

依存関係の確認(pom.xmlにpostgresqlの依存関係が正しく追加されているか)、
PostgreSQLが実行されているか、データベースが存在しているか、ファイルの接続許可設定に問題がないか、ポート番号の設定に間違いがないか確認したのですが、問題はありませんでした。

以前動作確認の作業をした際は問題なくできたのですが、どこにエラーの原因があるかわかりません。
他に確認すべき点はありますでしょうか。
よろしくお願いいたします。

下記がコンソールに出たエラーです。
```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
[2m2023-10-12T14:34:02.914+09:00[0;39m [31mERROR[0;39m [35m3612[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.b.d.LoggingFailureAnalysisReporter  [0;39m [2m:[0;39m 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
```

**Comment by masatanish** [comment]
> Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

というエラーからJava側でDB接続の設定がちゃんとされていないと言われているように見えます。
それ以上のことは与えられた情報からはわかりません。

エラーメッセージをググってみて引っかかるものを参照するなどしてみてください。
